### PR TITLE
Multiple tournaments

### LINKED ISSUE #18: Change UI to allow multiple duplicate strategies to be selected for a tournament
At the moment only one of each strategy may be selected for a new tournament.

### PR DESCRIPTION
**Pull request by nealedj**
Fixes #18

(I edited the above just so that waffle.io matches the PR to the issue correctly - Owen)

### CODE REVIEW

**Comment by drvinceknight** [comment]
This looks awesome! :+1: 

Minor thing I noticed when playing around with it: the boxes with the numbers don't quite fit?

screenshot 2015-06-22 08 45 25

Have you had a play with this @meatballs ?

**Comment by drvinceknight** [comment]
Not sure my screenshot has rendered properly: https://www.dropbox.com/s/pky0auiz362k1c1/Screenshot%202015-06-22%2008.45.25.png?dl=0

**Comment by nealedj** [comment]
Oh yeah - the CSS I used to hide those spinner arrows only work on webkit browsers.

Will just change it to a text input, that's more sensible.

**Comment by meatballs** [comment]
I'll have a look at this once #40 is merged - I suspect we'll get some merge conflicts because of the fix for #43

**Comment by meatballs** [comment]
I'm going to close this PR, create a new branch, merge the work done by @nealedj into that branch, fix the merge conflicts and push those changes.

Then we can have a good look and carry on the discussion!

**Pull request closed without merging**
