### PR TITLE
Tournament Results page showing real results 

### LINKED ISSUE #29: Tournament Results Page
- Create a page to show the results of a given tournament
- Return a link to the results page when a tournament completes rather than the current raw results data
- Show the results data on that page instead
- Pipe the results to the d3 graph and show that on the results page instead of the raw data
- Add a quick summary to show winner, loser etc
- Add a link to give raw results data

### LINKED ISSUE #43: Incorrect Scores
The scores appear to be allocated to the wrong players:

Create a tournament with
- players: Alternator, Cooperator, Defector and TitForTat
- turns: 10
- repetitions: 3

The results from djaxelrod are:

```
{"meta": 
{"definition": {"turns": 10, "repetitions": 3, "noise": 0.0},
"cheating_strategies": ["Darwin", "Geller", "Geller Cooperator", "Geller Defector", "Mind Bender", "Mind Controller", "Mind Reader", "Mind Warper", "Protected Mind Reader"]},
"results": [
{"player": "Defector", "scores": [2.433333333333333, 2.433333333333333, 2.433333333333333]
{"player": "Alternator", "scores": [1.5, 1.5, 1.5]}, 
{"player": "Cooperator", "scores": [2.066666666666667, 2.066666666666667, 2.066666666666667]}, 
{"player": "Tit For Tat", "scores": [3.1333333333333333, 3.1333333333333333, 3.1333333333333333]}]}
```

Create the same tournament within the axelrod library:

```
players=[axelrod.Alternator(), axelrod.Cooperator(), axelrod.Defector(), axelrod.TitForTat()]
t=axelrod.Tournament(players=players, turns=10, repetitions=3)
t.play()
t.result_set.normalised_scores
```

which gives the following results:

```
[[2.433333333333333, 2.433333333333333, 2.433333333333333], 
[1.5, 1.5, 1.5], 
[3.1333333333333333, 3.1333333333333333, 3.1333333333333333],
[2.066666666666667, 2.066666666666667, 2.066666666666667]]
```

 to confirm the order of the results:

```
t.players
```

gives:

```
[Alternator, Cooperator, Defector, Tit For Tat]
```

So, for example, it's Cooperator that scores [1.5, 1.5, 1.5] not Alternator as DjAxelrod shows.

### PR DESCRIPTION
**Pull request by mmcardle**
fixes #29 
fixes #43

### CODE REVIEW

**Comment by meatballs** [comment]
I've been away for a couple of days, but I should get a chance to have a look at this tomorrow.

**Comment by meatballs** [comment]
I think there are two things left to do on this before it's ready to merge:
- The vertical axis title on the graph needs to pick up the actual turns and repetitions rather than quoting the defaults
- The players need to be sorted by rank so that the winner appears at the left

**Comment by mmcardle** [comment]
Agreed - also do we need to display the raw results and winner/loser from points in the original issue?

**Comment by meatballs** [comment]
I think we can dispense with the winner/loser for now and create a new issue if anyone particularly wants it

I'll stick a link to the raw results into the header info at the top of the page.

**Comment by meatballs** [comment]
I've stripped the defaults out of the axis title on the graph and simply quoted the actual definition details in the top pane of the page

I've also added the definition into the results json, but it's not being used by the graph.

**Comment by meatballs** [comment]
I'm done with this - but I've probably done too much on it to be the one that reviews and merges it.

**Comment by meatballs** [comment]
Fixes #43

**Comment by drvinceknight** [comment]
This looks great _but_ the axes is not quite correct: https://www.dropbox.com/s/v3wgofi1ouva0ok/Screenshot%202015-06-22%2020.24.45.png?dl=0

That isn't the Mean Score per game...

**Comment by drvinceknight** [comment]
Here's the full screenshot with the 3 strategies:

screenshot 2015-06-22 20 27 23

The defector against the cooperator would get 5s per game and (5 + 1) / 2=3 per game so a mean of 4 per game.

The raw data (so cool that we can just pull that out) looks good though:

```
{"meta": {"definition": {"turns": 200, "repetitions": 10, "noise": 0.0}, "cheating_strategies": ["Darwin", "Geller", "Geller Cooperator", "Geller Defector", "Mind Bender", "Mind Controller", "Mind Reader", "Mind Warper", "Protected Mind Reader"]}, "results": [{"player": "Defector", "scores": [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]}, {"player": "Alternator", "scores": [2.25, 2.25, 2.25, 2.25, 2.25, 2.25, 2.25, 2.25, 2.25, 2.25]}, {"player": "Cooperator", "scores": [0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75]}]}
```

Here's the similar output from running (just from `import axelrod`):

```
>>> import axelrod
>>> strategies = [axelrod.Defector(), axelrod.Cooperator(), axelrod.Alternator()]
>>> tournament = axelrod.Tournament(strategies)
>>> results = tournament.play()
>>> results.normalised_scores
[[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0], [0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75], [2.25, 2.25, 2.25, 2.25, 2.25, 2.25, 2.25, 2.25, 2.25, 2.25]]
```

So it's just a question of scaling the axes... Apologies if I've missed a conversation here and this isn't for this PR.

**Comment by meatballs** [comment]
Ah yes! I just went with the text that was already there without thinking about it - Never a good thing.

What would you suggest instead?

**Comment by meatballs** [comment]
I can see the screenshot now. Not just a wording issue!

**Comment by drvinceknight** [comment]
Yeah it's an issue of getting the the scale right... To make progress on #42, we could merge this and open an issue about the axes scale?

**Comment by meatballs** [comment]
I think that might be wise. There are several bugs in vis.js and lots of things that jslint is complaining about. I can also see that it has 200 hard coded in here: https://github.com/Axelrod-Python/DjAxelrod/blob/master/static-dev/js/vis.js#L219 and that's possibly the number of turns.

I think it needs some tidying up! (Also, as I may have mentioned, I hate javascript and this would be an excellent piece of procrastination to avoid me having to look at it).

**Comment by drvinceknight** [comment]
Ok cool, I'll open the issue now with my particular point and let you add those points :)

**Pull request merged**
