### PR TITLE
Adds Vagrant virtual machine

### LINKED ISSUE #6: Vagrant Virtual Machine
I think we should configure a vagrant VM for the project in order to:
- Simplify the configuration for developers - it will all be done on the vm and provisioned by vagrant
- Ensure that all developers are using the same environment

### PR DESCRIPTION
**Pull request by meatballs**
Fixes #6

### CODE REVIEW

**Comment by meatballs** [comment]
I'd appreciate somebody else running through the installation process as per the instructions and confirming (or not) that it's all working correctly before this is merged.

**Comment by drvinceknight** [comment]
I've assigned that to myself. This week is tricky though but will get there as soon as I can.

**Comment by meatballs** [comment]
Anyone else able to have a look at this too?
- Checkout branch 6
- Follow the instructions in README.rst
- Add a comment here to let me know how it goes

(All working fine on my Macbook. Views from any Windows users would be useful).

**Comment by langner** [comment]
Not me. Sorry, but I generally will not be contributing to any repos except https://github.com/Axelrod-Python/Axelrod

**Comment by drvinceknight** [comment]
Let me ping @jasyoung314 and @geraintpalmer. Would be great for them to see some of the django wizardry. (I still aim to get to this)

**Comment by drvinceknight** [comment]
Just started to try this between things. Had an error: any of below helpful or is this something my end?

```
✘ 09:52 DjAxelrod (6) vagrant up                                                                                                      │
Bringing machine 'default' up with 'virtualbox' provider...                                                                           │
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...                                              │
    default: Box Provider: virtualbox                                                                                                 │
    default: Box Version: >= 0                                                                                                        │
==> default: Loading metadata for box 'ubuntu/trusty64'                                                                               │
    default: URL: https://atlas.hashicorp.com/ubuntu/trusty64                                                                         │
==> default: Adding box 'ubuntu/trusty64' (v20150420.1.2) for provider: virtualbox                                                    │
    default: Downloading: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/20150420.1.2/providers/virtualbox.box               │
==> default: Successfully added box 'ubuntu/trusty64' (v20150420.1.2) for 'virtualbox'!                                               │
There are errors in the configuration of this machine. Please fix                                                                     │
the following errors and try again:                                                                                                   │
                                                                                                                                      │
shell provisioner:                                                                                                                    │
* `path` for shell provisioner does not exist on the host system: /Users/vince/DjAxelrod/provision/initial.sh                         │
* `path` for shell provisioner does not exist on the host system: /Users/vince/DjAxelrod/provision/zsh/install_zsh.sh                 │
* `path` for shell provisioner does not exist on the host system: /Users/vince/DjAxelrod/provision/postgresql/install_postgresql.sh   │
* `path` for shell provisioner does not exist on the host system: /Users/vince/DjAxelrod/provision/django/install_django.sh
```

**Comment by drvinceknight** [comment]
Mac OS 10.10.2

**Comment by meatballs** [comment]
Thanks!

lt looks like the submodule folder (provision) is empty. I'll add something to the instructions for those who already have the repo cloned - at the moment the --recursive option sorts this out for a new user but doesn't deal with an existing one.

**Comment by meatballs** [comment]
```
git submodule init
git submodule update
vagrant up
```

should do it

**Comment by drvinceknight** [comment]
Not quite there yet:

```
✘ 09:55 DjAxelrod (6) git submodule init                                                                                              │tig: Not a git repository
Submodule 'provision' (https://github.com/meatballs/vagrant-provisioning.git) registered for path 'provision'                         │✘ 09:51 ~
10:10 DjAxelrod (6) git submodule update                                                                                              │
Cloning into 'provision'...                                                                                                           │
remote: Counting objects: 171, done.                                                                                                  │
remote: Compressing objects: 100% (116/116), done.                                                                                    │
remote: Total 171 (delta 66), reused 0 (delta 0), pack-reused 46                                                                      │
Receiving objects: 100% (171/171), 18.88 KiB | 0 bytes/s, done.                                                                       │
Resolving deltas: 100% (78/78), done.                                                                                                 │
Checking connectivity... done.                                                                                                        │
Submodule path 'provision': checked out '76299324c7180b9c9358eb33d6e6357c791e5eac'                                                    │
10:10 DjAxelrod (6) vagrant up                                                                                                        │
Bringing machine 'default' up with 'virtualbox' provider...                                                                           │
==> default: Importing base box 'ubuntu/trusty64'...                                                                                  │
==> default: Matching MAC address for NAT networking...                                                                               │
==> default: Checking if box 'ubuntu/trusty64' is up to date...                                                                       │
==> default: Setting the name of the VM: DjAxelrod_default_1429780233713_56102                                                        │
==> default: Clearing any previously set forwarded ports...                                                                           │
==> default: Clearing any previously set network interfaces...                                                                        │
==> default: Preparing network interfaces based on configuration...                                                                   │
    default: Adapter 1: nat                                                                                                           │
==> default: Forwarding ports...                                                                                                      │
    default: 8001 => 8000 (adapter 1)                                                                                                 │
    default: 5432 => 8432 (adapter 1)                                                                                                 │
    default: 22 => 2222 (adapter 1)                                                                                                   │
==> default: Booting VM...                                                                                                            │
==> default: Waiting for machine to boot. This may take a few minutes...                                                              │
The guest machine entered an invalid state while waiting for it                                                                       │
to boot. Valid states are 'starting, running'. The machine is in the                                                                  │
'poweroff' state. Please verify everything is configured                                                                              │
properly and try again.                                                                                                               │
                                                                                                                                      │
If the provider you're using has a GUI that comes with it,                                                                            │
it is often helpful to open that and watch the machine, since the                                                                     │
GUI often has more helpful error messages than Vagrant can retrieve.                                                                  │
For example, if you're using VirtualBox, run `vagrant up` while the                                                                   │
VirtualBox GUI is open.
```

**Comment by meatballs** [comment]
something nasty has happened to virtualbox there. Not seen that before. Try firing up the virtualbox gui and watching it as you run:

```
vagrant destroy
vagrant up
```

and/or starting the vm from the virtualbox gui

**Comment by drvinceknight** [comment]
Just updating virtualbox...

**Comment by drvinceknight** [comment]
Happy for me to merge in the PR?

**Comment by meatballs** [comment]
go for it

**Pull request merged**
